### ISSUE TITLE
multi_argument() with the only positional argument list fails in MSVC Debug.

### ISSUE THREAD

**Issue by wiluite** [morrisfranken/argparse#12]
If you have the only positional argument list and use multi_argument():
`std::vector<std::string>& fff = arg("blah-blah-blah").multi_argument();`
and *no use* the last one
`std::string & last = arg("blah");`

then there are some MSVC STL assert expectations somewhere in the guts of std::vector...

> ..VC\Tools\MSVC\14.34\31931\include\vector
> Line: 1949
> Exception: vector subscript out of range

Well, no problems with the other build tools or modes in this case.

So, I have no sufficient skills to fix that somehow.
Could you look?

**Comment by morrisfranken** [comment]
Hey @wiluite , thanks for reporting this. I looked into this and it seems to be related with an unnecessary out-of-bounds check on windows in debug mode. I've now pushed an update, let me know if that works for you.

~Morris

**Comment by wiluite** [comment]
Yes, it works. Thank you!
