### ISSUE TITLE
Named positional arguments

### ISSUE THREAD

**Issue by stefvanson** [morrisfranken/argparse#14]
Hi Morris,

I'd like to add support for named positional arguments. A more elaborate explanation and the proposed changes can be found in https://github.com/morrisfranken/argparse/pull/13, but I couldn't add a reviewer, so I wasn't sure if it would be noticed. Could you have a look?

Thanks in advance,
Stef

**Comment by morrisfranken** [comment]
Hi Stef,

Thanks for the pull request! This looks great and will indeed gives a much clearer help output. I also think your approach of choosing the overloaded function is the best to make it backwards compatible. 

As for the further suggestions:
  - Omitting "Options" from the help if there are no options  
  - Updating the help for subcommands from Usage: subcommand arg0 ... to Usage: program subcommand arg0 ...
Probably I would refactor a little bit to make it easy to test the generated help
   
Both look good to me, and should be easy to fix. Thanks for the suggestion, I will have a look at this later

I've just merged your PR to master, thanks again for the PR!

~Morris
