### ISSUE TITLE
Subcommand documentation improvement

### ISSUE THREAD

**Issue by MarcelFerrari** [morrisfranken/argparse#21]
Hi all,

thanks for developing this parser. It is by far the simplest to use that I was able to find for C++. I have a small suggestion to improve the documentation for subcommand support.

Please include the alternative way of calling subcommands documented [here](https://github.com/morrisfranken/argparse/blob/master/examples/argparse_subcommands.cpp) as a comment:

```
// Alternative way to run subcommands
//    if (args.commit.is_valid) {
//        std::cout << "running commit with the with the following message: " << args.commit.message << std::endl;
//    } else if (args.push.is_valid) {
//        std::cout << "running push with the following parameters" << std::endl;
//        args.push.print();
//    } else {
//        std::cout << "No subcommand given" << std::endl;
//    }
//    return 0
```

I was about to switch to a different argument parser because I hated having to delegate calling subcommand functions to the parser's `run_subcommands()` method. The reason is that I had to pass additional parameters to these functions that are not part of the arguments of the program, which required me to go through static global variables when using `run_subcommands()`.

Luckily I saw this one comment and found out there is this much more flexible alternative.

Thanks,

Marcel

**Comment by morrisfranken** [comment]
Hi @MarcelFerrari , thanks for the suggestion! I've now added this to the documentation
