### ISSUE TITLE
`operator T&()` combined with `set_default()` doesn't work if the input value's type isn't the same as desired variable type

### ISSUE THREAD

**Issue by mhaseeb123** [morrisfranken/argparse#5]
Hi,

I would like to report a (probably minor) bug with `operator T&()` and `.set_default()`. If the default value doesn't match the type of the desired variable's data type, the `operator T&()` returns a `0` instead of the provided value. For example:

The following code runs fine

```cpp
    float &alpha          = kwarg("a,alpha", "An optional float value").set_default(0.5f); # ok
```

but the following code return `args.alpha = 0`.

```cpp
    float &alpha          = kwarg("a,alpha", "An optional float value").set_default(0.5); # args.alpha = 0
```

Providing default value as a `string` instead of a numeric 0.5 value works fine as the `covert` function takes care of it.

More examples:

```cpp
    int &val                  = kwarg("b,beta", "An optional int value").set_default(20.0) # will not work
    int &val                  = kwarg("b,beta", "An optional int value").set_default((int)(20.0)) # will work

     short &val                  = kwarg("g,gamma", "An optional short value").set_default(20) # will not work
     short &val                  = kwarg("g,gamma", "An optional short value").set_default(short(20)) # will work
```

Summary: The `operator T&()` method doesn't return the correct default value if the type of the numeric value in `set_default` is not the same as the desired output variable.

**Comment by mhaseeb123** [comment]
Update: So I figured out that the problem arises as the compiler assumes `0.5` to be `double` type implicitly and not float unless `f` is specified. So I dug a bit in the code and I think this behavior is intended and comes from this check:

```cpp
std::is_same<typename std::remove_all_extents<T>::type, char>::value
```

This check seems a bit too strict as it is quite easy to mess up. For example, for an `int` type argument, providing `20.0` as default will not work. Will try to think of an alternative check where at least there is some relaxation for numeric types like (short, int, float, double) providing implicit conversion. 

Actually this make `short` types very interesting as the default value will be treated as `int` instead of short unless explicitly typecasted (short)20

**Comment by morrisfranken** [comment]
Hi [mhaseeb123](https://github.com/mhaseeb123), 

Thanks for your detailed report. The `set_default` function indeed expects exactly the same type as the requested type. The reason for this is because the requested type returned by `operator T&()` is not known when setting the default type. As such, it simply assumes they are the same type and performs a binary typecast which may or may not work.
```
        void set_default(const std::unique_ptr<ConvertBase> &default_value) override {
            data = ((ConvertType<T>*)(default_value.get()))->data;
        }
```

To solve this I've added a check to verify if the requested type and the default type are the same, if not, it will perform a conversion from string instead:
```
        void set_default(const std::unique_ptr<ConvertBase> &default_value, const std::string &default_string) override {
            if (this->get_type_id() == default_value->get_type_id())    // When the types do not match exactly. resort to string conversion
                data = ((ConvertType<T>*)(default_value.get()))->data;
            else
                data = get<T>(default_string);
        }
```

You can pull the latest update and verify it this solves the issue for you.
